#!/usr/bin/env python3
"""Regenerate with: python3 scripts/generate-crc32-table.py > src/crc32_table.h"""

tables = []
base = []
for value in range(256):
    for _ in range(8):
        value = (value >> 1) ^ (0xEDB88320 if value & 1 else 0)
    base.append(value)
tables.append(base)
for _ in range(7):
    tables.append([(value >> 8) ^ base[value & 255] for value in tables[-1]])

print("// Generated by scripts/generate-crc32-table.py; do not edit by hand.")
print("// Reflected IEEE CRC-32. Table N advances a byte by N additional zero bytes.")
print("static const uint32_t crc32_table[8][256] = {")
for table in tables:
    print("    {")
    for i in range(0, 256, 4):
        print("        " + ", ".join(f"0x{value:08X}u" for value in table[i:i + 4]) + ",")
    print("    },")
print("};")
